# Generated by Django 4.2.11 on 2026-01-13 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_type', models.CharField(choices=[('BCG', 'BCG'), ('HepB', 'Hepatitis B'), ('OPV', 'Oral Polio Vaccine'), ('DPT', 'Diphtheria, Pertussis, Tetanus'), ('Hib', 'Haemophilus influenzae type b'), ('PCV', 'Pneumococcal Conjugate'), ('Rotavirus', 'Rotavirus'), ('Measles', 'Measles / MMR'), ('Yellow Fever', 'Yellow Fever'), ('COVID-19', 'COVID-19'), ('Flu', 'Influenza'), ('HPV', 'Human Papillomavirus'), ('Other', 'Other')], max_length=50)),
                ('date_administered', models.DateField()),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
